### ISSUE TITLE
It could be good to have an example of dealing with categories that have spaces 

### ISSUE THREAD

**Issue by dicook** [robjhyndman/compenginets#4]
For example,  an error is generated when

```
cets_animals <- get_cets("animal sounds", maxpage = 53)
Error in curl::curl_fetch_memory(url, handle = handle) : 
  URL rejected: Malformed input to a URL function
```

This works, though:

`cets_animals <- get_cets("animal%20sounds", maxpage = 53)`

**Comment by robjhyndman** [comment]
Thanks. Now fixed in https://github.com/robjhyndman/compenginets/commit/35851f1e9436ebba7e33ade9306c0176d95cd9ac
